README.md, README.next.md
I've written a [plugin](https://github.com/venantius/vim-eastwood) that automatically runs `eastwood.lint/eastwood` on the current Vim buffer through a vim-fireplace REPL connection, and offers Syntastic bindings. It'd be great if this could be linked to from the Eastwood README. Happy to make tweaks or adjustments if needed.
=> Add vim-eastwood mention in editors section

src/eastwood/analyze_ns.clj, src/eastwood/lint.clj, src/eastwood/linters/misc.clj, test/eastwood/test/linters_test.clj
I'm looking at getting eastwood to work on .cljc files with reader conditionals. (See #179) For starters, I spotted that reader options weren't being passed correctly to `clojure.tools.namespace.file/files-and-deps`. There's still more that doesn't work, but this is a start.
=> Reader conditional fixes

src/eastwood/linters/misc.clj
It looks like `:is-dynamic` may have gone away, or at least isn't doing what we want.
Fixes #212
=> [#212] Make use if dynamic? on the instance Var

cases/testcases/unusednss3.clj, src/eastwood/linters/unused.clj, test/eastwood/test/linters_test.clj
This should fix #162. Let me know what you think.
=> Fix false positive re: protocols in unused-namespaces linter.

resource/eastwood/config/third-party-libs.clj
This hopefully addresses #161.
=> Added a rule to exclude timbre's profiling macros

README.md
I noticed in the logs for Deps Versions that there was an error thrown trying to load https://versions.deps.co/jonase/eastwood a few weeks ago. I think I've resolved that error now, so I'm providing a PR. If this wasn't a maintainer checking this, and you don't want to switch, feel free to close this.
=> Update to Deps Versions dependency status

src/eastwood/linters/typos.clj
It's common to find codebases which use a namespaced version of `:else` or `:default` in cond, resulting
in warnings about the expression always being logically true. 
> constant-test: Test expression is always logical true or always logical false:
This change would test against the non-namespaced version of the keyword as well.
=> typos: allow namespaced forms for ::else, ::default, and ::otherwise.

README.md, project.clj, src/eastwood/analyze_ns.clj, src/eastwood/error_messages.clj, src/eastwood/lint.clj, src/eastwood/linters/misc.clj, src/eastwood/linters/typos.clj, src/eastwood/util.clj, src/leiningen/eastwood.clj, test/eastwood/test/linters_test.clj
- create new ns `error-mesages` to hold error-reporting
- make main code less side-effecty by making `lint-ns` return values
and have callers print out messages
- suddenly `redefd-vars` started reporting errors
=> Extract common code related to error-reporting into own ns

resource/eastwood/config/clojure.clj
- `as->` was not handled like `cond->`
- `coll-of` was not handled like `keys` in spec
related to https://github.com/jonase/eastwood/issues/227
=> Fix warnings on clojure macro expansions

src/eastwood/error_messages.clj
The middle arg of eastwood.error-messages/format-exception is unused, so we remove it
to fix the bug.
Fixes #268
=> report-analyzer-exception calls eastwood.error-messages/format-exception with 2 args.

resource/eastwood/config/clojure.clj
The arglist in clojure specify `[xform* coll]`, so eastwood takes this as 2 arguments but it is really a list of 0 or more transducers and a collection at the end.
AFAIK, there no better way to express this in clojure so I am just defaulting to the real arguments defined in clojure source code `[& xforms]`
You can check that this fixed my project lint errors in my travis [history](https://travis-ci.org/hiposfer/kamal)
Hope it helps
=> disable warning for eduction arguments

cases/testcases/analyzererror.clj, src/eastwood/lint.clj
Add a test case that will always throw an analysis error.
Before this commit, eastwood would swallow analyzer exceptions:
```
$ lein eastwood "{:namespaces [testcases.analyzererror]}"
== Eastwood 0.3.0-SNAPSHOT Clojure 1.8.0 JVM 1.8.0_144
== Linting testcases.analyzererror ==
== Warnings: 0 (not including reflection warnings)  Exceptions thrown: 0
```
After this commit, it reports them:
```
$ lein eastwood "{:namespaces [testcases.analyzererror]}"
== Eastwood 0.3.0-SNAPSHOT Clojure 1.8.0 JVM 1.8.0_144
== Linting testcases.analyzererror ==
Exception thrown during phase :analyze+eval of linting namespace testcases.analyzererror
Got exception with extra ex-data:
msg='Class not found: no.such.java.class'
(keys dat)=(:class :file :end-column :column :line :end-line)
ExceptionInfo Class not …
```
=> Report analyzer exceptions when linting.

src/eastwood/linters/unused.clj
Not sure if this is in scope for Eastwood or not, but I found this helpful on an internal fork.
If linters return data, they can be used programmatically.
In my case, I used this additional data to collect all unused namespaces and automatically rewrite the namespace form to not include those unnecessary namespaces.
=> Add data to unused namespace linter.

src/eastwood/linters/implicit_dependencies.clj, test/eastwood/test/implicit_dependencies_linter_test.clj
Ref: https://github.com/jonase/eastwood/issues/288
I ran the linter against carmine as suggested by @jafingerhut and there are no warnings from the implicit-dependency linter after these changes.
I didn't update the changelog since 0.3.2 hasn't been released yet.
Thanks!
=> Implicit dependency linter should ignore vars within macros defined in other namespaces.

changes.md, resource/eastwood/config/clojure.clj
I ran into a nearly identical situation as @valerauko in [#273](https://github.com/jonase/eastwood/issues/273) (minus the `defstate` issue). This was the most narrowly targeted suppression that I was able to come up with and I confirmed this worked on my codebase using a custom config file.
=> Suppress ":constant-test" warning for "or" inside clojure.spec's "coll-of"

changes.md, resource/eastwood/config/clojure.clj
As described in #273, mount's defstate is reported with a multiple-def warning.
defstate uses defonce internally, but for some reason it isn't recognized as its expansion (even with very large depth).
The simplest solution is to add defstate to the list of the def* exception.
=> Disable defonce warning for mount.core/defstate

src/eastwood/analyze_ns.clj, src/eastwood/error_messages.clj, src/eastwood/lint.clj, src/eastwood/linters/implicit_dependencies.clj, src/eastwood/linters/misc.clj, src/eastwood/reporting_callbacks.clj, src/eastwood/util.clj, src/eastwood/version.clj, test/eastwood/lint_test.clj, test/eastwood/test/implicit_dependencies_linter_test.clj, test/eastwood/test/linters_test.clj
This commit removes most of the callback code used for reporting in
Eastwood, in favour of a set of multimethods found in the
`reporting-callbacks` ns
Also, state-handling has gone from atoms to a more functional
approach, and error handling is now largely done by exceptions rather
than passing maps with magic keys.
An effort has been done to remove the passing of `opts` and rather
extract the needed values from `opts` before calling the next function.
**Replace this placeholder text with a summary of the changes in your PR.
The more detailed you are, the better.**
Thanks!
=> Remove callbacks + cleanups

README.md, src/eastwood/lint.clj
The current implementation only supports the main opts to be a string,
which should be a stringified EDN. This patch keeps this feature for
backward compatibility and adds the ability to send a Clojure map
directly. This allows us to declare main-opts in a Clojure deps project
like this:
```
:main-opts ["-m" "eastwood.lint"
{:source-paths ["src" "test" "standalone" "dev"]
:config-files ["resources/eastwood_config.clj"]
:exclude-linters [:unused-ret-vals]}]}
```
String version is also supported in order to be backward compatible:
```
:main-opts ["-m" "eastwood.lint" "{:source-paths,[\"src\",\"test\",\"standalone\",\"dev\"],:config-files[\"resources/eastwood_config.clj\"],:exclude-linters[:unused-ret-vals]}"]}
```
=> Support string or map for main opts

README.md
There was no intrinsic link between `:only-modified` flag and the readme text that describes the functionality.
Also the heading implied that the rest of the content was about the same subject, so I added a new misc header.
=> Add info on how to use only-modified

resource/eastwood/config/third-party-libs.clj
Disable warning for false positive macro expanding for Carmine
=> Disable warning for false positive macro expanding for Carmine

changes.md, src/eastwood/util.clj
Applies suggestion made in #317, solving the issue.
=> Reset warning-enable-config-atom before init

cases/testcases/wrongprepost2.clj, changes.md, src/eastwood/linters/typos.clj
Fixes #190 by ignoring any var marked as dynamic in `prepost`-linter.
Thanks!
=> [Fix #190] no warnings for dynamic vars in pre/post

changes.md, project.clj, src/eastwood/lint.clj, src/eastwood/util.clj, test-resources/eastwood/config/linter_executor.clj, test-resources/eastwood/test/linter_executor/sample_ns.clj, test/eastwood/linter_executor_test.clj
This PR introduces `set-linter-executor!` so that I can test out my tentative linter parallellism for a few weeks.
For extra context, I run Eastwood through a [rather heavy](https://github.com/nedap/formatting-stack/blob/5c6e1f11c6ec80475063df52e1aceaded8375aee/.circleci/config.yml) CI pipeline :)
Part of jonase/eastwood#339
---
=> Introduce `set-linter-executor!`

README.md
The example config source has a missing `"`. This fixes it.
=> Fix a missing quote in a code example

changes.md, src/eastwood/lint.clj, src/eastwood/reporting_callbacks.clj, test-resources/invalid/syntax.clj, test/eastwood/lint_test.clj
github.com/nedap/formatting-stack offers eastwood integration, we got a report of an unreported exception (https://github.com/nedap/formatting-stack/issues/159). 
I initially tried to fix it in this PR #332, but I deemed that too invasive as it was a breaking change.
The `:rethrow-exceptions?` option offers throwing any encountered exceptions during analysis/linting instead of only reporting them.
Thanks!
=> Introduce `:rethrow-exceptions?` option

src/eastwood/lint.clj, test/eastwood/lint_test.clj, test/eastwood/test/linters_test.clj
This allows to use topological dependency order, avoiding unlucky code loading by tools.analyzer.
Thanks!
Passing a vector of :namespaces allows to use a topological dependency order, avoiding unlucky code loading by tools.analyzer
=> Keep order for `:namespaces`-option

src/eastwood/reporting_callbacks.clj
Since #348 we noticed the exceptions are sometimes wrapped in a hashmap, which cannot be thrown. The presence of a `:exception`-key is not guaranteed, so `maybe-wrap-in-ex-info` was added to wrap the hashmap in ex-info.
Thanks!
=> Fix `:rethrow-exceptions?`-bug

cases/testcases/f08.clj, cases/testcases/imported_var.clj, changes.md, src/eastwood/linters/implicit_dependencies.clj, test/eastwood/test/implicit_dependencies_linter_test.clj
e.g. imported using #'potemkin/import-vars. fixes #307 as suggested [here](https://github.com/jonase/eastwood/issues/307#issuecomment-764304379)
I verified this change by loading eastwood with `[clojure.java-time "0.3.2"]` on it's classpath, and analyzing `(ns test (:require [java-time]))`;
First execution is against current master, second execution is against this fix.
**Replace this placeholder text with a summary of the changes in your PR.
The more detailed you are, the better.**
Thanks!
=> Improve `:implicit-dependencies` to support potemkin

.circleci/config.yml, project.clj, src/eastwood/linters/implicit_dependencies.clj, src/eastwood/util.clj, test/eastwood/test/implicit_dependencies_linter_test.clj
Fixes https://github.com/jonase/eastwood/issues/356
* temporarily change `:eval-in-leiningen true` to `false` (so that one doesn't use whatever Clojure version one's Lein is using)
* Run/observe these commands:
```shell
$ lein with-profile +1.9 test :only eastwood.test.implicit-dependencies-linter-test
Testing eastwood.test.implicit-dependencies-linter-test
Ran 1 tests containing 1 assertions.
0 failures, 0 errors.
$ lein with-profile +1.10 test :only eastwood.test.implicit-dependencies-linter-test
Testing eastwood.test.implicit-dependencies-linter-test
Ran 1 tests containing 2 assertions.
0 failures, 0 errors.
```
* Note how a 1 fewer assertion is run in the `+1.9` case.
=> Fix unintentional Clojure 1.10+ requirement

src/eastwood/passes.clj
Fixes https://github.com/jonase/eastwood/issues/355
This `println` was confusing. The reflection warnings mechanism already correctly informing end users of when some type hinting would be needed.
* Add the following namespace under Eastwood (and this branch):
```clj
(ns eastwood.foo
(:import
(java.nio.file Files OpenOption Path)))
(defn do-something [path x]
;; ...
(Files/write path (byte-array 10) (into-array OpenOption []))
;; ...
true)
```
* Run the following command:
* `lein eastwood "{:namespaces [eastwood.foo]}"`
* Note how no noisy outout is printed
* Note how the command correctly reports 0 exceptions, 0 warnings
=> Hide a println under the :debug mechanism

cases/testcases/unusednsimport/consumer1.clj, cases/testcases/unusednsimport/consumer2.clj, cases/testcases/unusednsimport/consumer3.clj, cases/testcases/unusednsimport/consumer4.clj, cases/testcases/unusednsimport/consumer5.clj, cases/testcases/unusednsimport/defrecord.clj, src/eastwood/linters/unused.clj, test/eastwood/test/linters_test.clj
Fixes jonase/eastwood#210
Closes https://github.com/jonase/eastwood/pull/351
=> `linters.unused`: account for imported classes

cases/testcases/large_defprotocol.clj, copied-deps/eastwood/copieddeps/dep2/clojure/tools/analyzer/jvm.clj, test/eastwood/lint_test.clj
This metadata, likely provenant from Eastwood's processing, was bloating code size, leading to "Method code too large!" exceptions.
...Metadata is only removed as a last resource. I also checked that basically all of the proposed metadata (`:arglists :file :line :column :end-line :end-column`) has to be removed and not just a subset. I guess every byte counts!
Fixes https://github.com/jonase/eastwood/issues/191
Fixes https://github.com/jonase/eastwood/issues/344
=> `analyze+eval`: fall back to evaluating a form with less metadata

README.md, doc/README.next.md, src/eastwood/linters/typos.clj
Fixes https://github.com/jonase/eastwood/issues/298
Closes https://github.com/jonase/eastwood/issues/306
Sadly, while I could reproduce the bug when checking cider-nrepl as a whole, I couldn't when extracting only the `cider.nrepl.middleware.stacktrace-spec-test` ns.
So I'm not sure we should bother growing the test suite.
I did add some strategic `assert`s, which of course are, in a way, 'inline tests' preventing a regression.
```
rm -rf ~/.m2/repository/jonase/
cd
git clone https://github.com/clojure-emacs/cider-nrepl xxx
cd xxx
git checkout b2c0b920d762fdac2f8210805df2055af63f2eb1
lein with-profile +1.9 eastwood '{:exclude-namespaces [cider-nrepl.plugin cider.nrepl.test-session]}'
```
```
cd <your Eastwood clone>
lein with-profile +eastwood-plugin install
lein with-profile +1.9 …
```
=> Strengthen `suspicious-is-forms`

README.md, cases/testcases/ignored_faults_example.clj, changes.md, src/eastwood/lint.clj, test/eastwood/lint_test.clj
Fixes #21
Closes https://github.com/jonase/eastwood/issues/187
Closes https://github.com/jonase/eastwood/issues/282
Closes https://github.com/jonase/eastwood/issues/165
The way I approached this fix was simple: making the 'ignoring' a property of the output (our emitted reports), not of the input (Clojure code).
Accordingly, end users don't have to add extraneous metadata/comments (which meaning can be unclear to newcomers, and importantly to other tooling, which might interpret it badly, clean it up, etc).
It isn't necessarily the last word on the topic of course, but this approach seems simple and non-invasive (vs. altering Clojure source code, and very plausibly our whole analysis/linting pipeline).
Importantly, as I view it it makes Eastwood a more viable tool for being run as a hard …
=> Implement `:ignored-faults` configuration  option

cases/testcases/const.clj, changes.md, src/eastwood/analyze_ns.clj, test/eastwood/analyze_ns_test.clj, test/eastwood/lint_test.clj
`^:const` is not part of any public API described in https://github.com/clojure/clojure-site.
However usage of it can be still found in the wild, perhaps influenced by past knowledge.
https://github.com/jonase/eastwood/issues/341 showed that attempting to process a defn having `^:const` would throw an exception.
This commit proposes removing that piece of metadata, since it doesn't alter semantics and saves the effort of investigating a more intrincate integration with tools.analyzer (for what I believe is not a public API anyway).
It's worth noting that https://clojure.org/reference/compilation#directlinking **is** a public API,
and something that can be used in production environments instead of `^:const`, without fearing a clash with Eastwood whatsoever.
Fixes …
=> [Fix #341] Remove `^:const` metadata prior to processing a given form

changes.md, src/eastwood/exit.clj, src/eastwood/lint.clj, src/eastwood/versioncheck.clj
Lein's `exit` results in more graceful exit program termination when using Eastwood as part of another plugin, higher-order task, etc.
Fixes https://github.com/jonase/eastwood/issues/244
=> [Fix #244] Use `leininen.core.main/exit` when suitable

.circleci/config.yml, README.md, changes.md, src/eastwood/util.clj
I've used `pmap` over the last 12 months, continuously (in CI and repls alike, across work/personal projects) observing no issues.
So it seems a safe and convenient default to improve.
`clojure.core/pmap` is not too bad of a choice (vs. other pmap-like functions) because its implementation caps the maximum amount of spawned threads to a number relative to CPU count.
So the workloads, which are CPU-bound, will be treated as such, without possibly hogging the OS with an excess of threads.
=> [Fix #339] Upgrade `linter-executor-atom` to `pmap`

.circleci/config.yml, README.md, changes.md
Makes it more comprehensible as it's a big release
Also downgraded the builds to xlarge (for those running Eastwood CI with a paid account) since 2xlarge is reserved for larger customers
=> Prettify changelog for 0.4.0

lein-eastwood/leiningen/eastwood.clj, src/eastwood/analyze_ns.clj, src/eastwood/error_messages.clj, src/eastwood/lint.clj, src/eastwood/linters/deprecated.clj, src/eastwood/linters/implicit_dependencies.clj, src/eastwood/linters/misc.clj, src/eastwood/linters/typetags.clj, src/eastwood/linters/typos.clj, src/eastwood/linters/unused.clj, src/eastwood/passes.clj, src/eastwood/reporting_callbacks.clj, src/eastwood/util.clj, src/eastwood/version.clj, src/eastwood/versioncheck.clj, test/eastwood/lint_test.clj, test/eastwood/linter_executor_test.clj, test/eastwood/test/analyze_ns_test.clj, test/eastwood/test/cc_compare.clj, test/eastwood/test/implicit_dependencies_linter_test.clj, test/eastwood/test/linters_test.clj
The lack of standardized formatting was making working on the codebase a bit painful - normally no-formatting means that I have to disable autoformatting, which in turns makes me format my changes manually.
Also the occasional choice of ns-aliases would confuse me :)
Commit summary:
* Reformat src, test
* Used:
* cljfmt
* refactor-nrepl for removing unused imports
* [how-to-ns](https://github.com/gfredericks/how-to-ns)
* Follow https://stuartsierra.com/2015/05/10/clojure-namespace-aliases
* Address some clj-kondo faults
All this was accomplished quite effortlessly with the tooling setup I happen to have at hand. Feedback welcome, I'd be happy to tweak things.
This PR's (low) impact can be best assessed by using `Hide whitespace changes`.
=> Formatting

cases/testcases/test_metadata_example.clj, changes.md, src/eastwood/linters/misc.clj, test/eastwood/lint_test.clj
=> `:bad-arglists`: fix false positive for defns with `^:test` metadata

.circleci/config.yml, cases/testcases/wrong_tag_example.clj, changes.md, project.clj, resource/eastwood/config/third-party-libs.clj, src/eastwood/linters/typetags.clj, src/eastwood/linters/typos.clj, src/eastwood/util.clj, test-resources/eastwood/config/disable_wrong_tag.clj, test-third-party-deps/eastwood/third_party_deps_test.clj, test-third-party-deps/testcases/speced_def_example.clj, test/eastwood/lint_test.clj
Supports the [speced.def](https://github.com/nedap/speced.def) library and also might be useful for other purposes.
Relatedly, now this third-party lib is exercised in CI, in an isolated job matrix. This way we can run foreign code resting assured that the presence of these libs doesn't affect the results of the main test suite.
This new matrix opens the door to exercising more third-party code e.g. core.async.
=> Make the `:wrong-tag` linter omittable

cases/testcases/are_true/green.clj, cases/testcases/are_true/red_one.clj, cases/testcases/are_true/red_three.clj, cases/testcases/are_true/red_two.clj, changes.md, resource/eastwood/config/clojure.clj, src/eastwood/linters/misc.clj, src/eastwood/linters/typos.clj, src/eastwood/util.clj, test/eastwood/analyze_ns_test.clj, test/eastwood/lint_test.clj, test/eastwood/linter_executor_test.clj
Supports a specific `clojure.test/are` pattern, as shown in the included tests.
...This pattern tends to fail better (else a test failure would show up twice), which is why it's a good idea for Eastwood to support it.
=> Make the `:suspicious-test` linter omittable

cases/testcases/clojure_test.clj, changes.md, resource/eastwood/config/clojure.clj, src/eastwood/linters/typos.clj, test/eastwood/lint_test.clj
* Closes https://github.com/jonase/eastwood/issues/116
* nothing had to be fixed; only proves that the bug is now absent
* Fixes https://github.com/jonase/eastwood/issues/207
* Fixes https://github.com/jonase/eastwood/issues/313
=> Fix various false positives for clojure.test

changes.md, src/eastwood/lint.clj, test-resources/eastwood/config/disable_wrong_tag_unrelated.clj, test-third-party-deps/eastwood/third_party_deps_test.clj, test/eastwood/lint_test.clj
It's akin to `:some-warnings`, but informs exclusively about exceptions.
This strengthens our tests, which relatedly, were missing a file under the `resource/` dir (thankfully, without impact).
=> `eastwood.lint/eastwood`: offer `:some-errors` key

cases/testcases/wrong_meta_on_macro_example.clj, changes.md, src/eastwood/linters/unused.clj, src/eastwood/util.clj, test-resources/eastwood/config/disable_unused_meta_on_macro.clj, test-resources/eastwood/config/disable_unused_meta_on_macro_unrelated.clj, test/eastwood/lint_test.clj
Fixes https://github.com/jonase/eastwood/issues/303
=> [Fix #303] Make the `:unused-meta-on-macro` linter omittable

project.clj, src/eastwood/util.clj, test-third-party-deps/eastwood/third_party_deps_test.clj, test-third-party-deps/testcases/timbre_example.clj, test-third-party-deps/testcases/tufte_example.clj, test/eastwood/lint_test.clj
> Closes https://github.com/jonase/eastwood/issues/161
2 commits:
Despite https://github.com/jonase/eastwood/pull/375, it was still possible to refer to non-existing config files in tests, simply because the configs are read in a try/catch that would swallow exceptions.
Now that section of the code rethrows exceptions _iff_ we are running the test suite.
Nothing had to be fixed.
This addition simply proves that Eastwood can in fact handle said libs.
Interestingly it also exercises tools.analyzer more by giving it some extra real-world libs to run in CI.
=> Test suite improvements

src/eastwood/linters/typetags.clj, test/eastwood/lint_test.clj
On certain inputs, they would try applying `pr-str` over a huge (or infiinite - I don't know) object and OOM accordingly.
I'd be inclined to remove the println and simply let users report issues.
A `println` can be dangerous otherwise and most users typically cannot make much use of it anyway.
Would break the clojure 1.7 job.
=> Remove some `println`s

cases/testcases/let/green.clj, cases/testcases/let/red.clj, changes.md, src/eastwood/linters/typos.clj, test/eastwood/lint_test.clj, test/eastwood/linters/typos_test.clj
=> [Fix #383] Fix a false positive in `let` destructuring

cases/testcases/cond/green.clj, resource/eastwood/config/clojure.clj, src/eastwood/linters/typos.clj, src/eastwood/util.clj, test/eastwood/lint_test.clj
> Closes #169
This commit does two things:
* Prove that the three bugs described in #169 are fixed
* (have been for a long time)
* Add and support a `:qualifier` value for `:constant-test`, so that only `true` will be accepted a `:constant-test` for `cond->`
=> [Fix #169] Prove that various cond, cond-> forms work correctly

cases/testcases/is_false/green.clj, changes.md, resource/eastwood/config/clojure.clj, src/eastwood/linters/typos.clj, test/eastwood/lint_test.clj
Closes https://github.com/jonase/eastwood/issues/384
=> [Fix #384] Support `is false` pattern

cases/testcases/while_true/green.clj, cases/testcases/while_true/red.clj, changes.md, resource/eastwood/config/clojure.clj, test/eastwood/lint_test.clj
Closes https://github.com/jonase/eastwood/issues/386
=> [Fix #386] Support `(while true)` pattern

cases/testcases/bytes_class/green.clj, cases/testcases/wrongtag.clj, changes.md, src/eastwood/linters/typetags.clj, test/eastwood/lint_test.clj, test/eastwood/test/linters_test.clj
> Fixes https://github.com/jonase/eastwood/issues/385
This false positive's origin can be tracked down to this commit:
https://github.com/jonase/eastwood/commit/7c0f432ee1be4748fb6cb765089872cd7640d27e
I think that commit made the mistake of conflating "this pattern should not trigger an exception" with "with pattern should trigger a linter fault".
Usages in the wild such as the following show that in fact the pattern is functional:
* https://github.com/mikera/core.matrix/blob/0a35f6e3d6d2335cb56f6f3e5744bfa1dd0390aa/src/main/clojure/clojure/core/matrix/impl/double_array.clj#L124
* https://github.com/immutant/immutant/blob/6ff8fa03acf73929f61f2ca75446cb559ddfc1ef/web/src/immutant/web/async.clj#L198
* https://github.com/sunng87/ring-jetty9-adapter/blob/95bf989216cb01986615c40b4cc50178d1578d …
=> [Fix #385] Support an edge case for `extend-protocol`
